### ISSUE TITLE
Code errors when running: node index.js

### ISSUE THREAD

**Issue by nabbl** [node-enocean/node-enocean#29]
Hi,

Code doesn't seem to work. I get syntax errors (at least on windows ...)

Code in question:
**index.js:**
```javascript
socket.on( "get-last-sensor-value" , async function( id ) {
			socket.emit("last-sensors-value", await this.getLastValues( id ) ) // returns info for one single sensor
```

**memory.js**
```javascript
	app.getLastValues = async function(id){
		return await getLastData(id)
	}
```

**Comment by Holger-Will** [comment]
what node version and node-enocean version are you running?

**Comment by nabbl** [comment]
16 Aug 19:04:45 - [info] Node-RED version: v0.17.5
16 Aug 19:04:45 - [info] Node.js  version: v6.9.4

**Comment by Holger-Will** [comment]
ok, async await only works for node >= 7.6.0. before that, you have to start your project with the harmony flag... 

    node index.js --harmony-async-await

i should make this more clear in the read me, or set the min version acordingly...

btw, there is a 3.0.0beta of node enocean with a new generic eep decoder which in theory should be able to parse all eep's...it's not completely done but woks just great for simple telegram. Only some edge cases do break currently. You can install it with 

    npm i -S node-enocean@3

**Comment by nabbl** [comment]
I tried to install it like that. But it also tries to install a very old node-serialport version (and then tries gyp to recompile)

but this is with node 8.6.0
Maybe it would be a good idea anyway to update the serialport version to the newest one. Shouldn't be too much code change anyway.

**Comment by Holger-Will** [comment]
i just published version 3.0.1 (no beta tag) which uses serialport 4.x
this works well with node 8.x, adds some new features and better error handling.

the problem with 5.x is that i use a third party serialport parser which does not work wth 5.x yet...

**Comment by Holger-Will** [comment]
leaving this open for a while for reference...

**Comment by Holger-Will** [comment]
https://github.com/RafaelKa/node-serialport-enocean-parser/issues/8

**Comment by Jean-PhilippeD** [comment]
Hello,

I have the same issue with async/await features not supported on node app I use which is release with node v6 version.

How could I do to have a compatibility ? I've trie the option --harmony-async-await but It seems to be an unknown option ?

```
node --harmony-async-await app.js 
node: bad option: --harmony-async-await

```

**Comment by Holger-Will** [comment]
this should no longer be an issue for current node versions...
