### ISSUE TITLE
Config is now broken

### ISSUE THREAD

**Issue by AlCalzone** [node-enocean/node-enocean#34]
Apparently, the recent fixes in 3.2.0 broke the configuration. I can't even initialize the module now. It seems the memory module is now initialized with `memoryDirectoryPath` set to `undefined`, which causes the default paths to not be applied.
The config object looks as follows:
```
{ sensorFilePath: 'D:\\test\\node-enocean-bug\\node_modules\\node-enocean/modules/knownSensors.json',
  memoryDirectoryPath: undefined }
```
which causes `config.hasOwnProperty` to succeed.

The fix is rather easy, change line 31 to 
```
var memoryDir = config.memoryDirectoryPath || path.join(__dirname,"../memory")
```
and line 34 should probably be changed the same way for good measure.

**Comment by Holger-Will** [comment]
sorry ;-) fixed. published 3.2.1
