### ISSUE TITLE
How can we send data to a device

### ISSUE THREAD

**Issue by Jean-PhilippeD** [node-enocean/node-enocean#39]
I've tryied to use the node-enocean-button to send to my "F6" device but I don't understand how does it work ?

I don't see where I define the Id of the targeted device ?

**Comment by Jey-Cee** [comment]
You do not define the id of the targeted device. The targated device is responding to the telegram that your are sending.
This is because your USB Gateway has his own address, which is known by the receiver. 
This only works if you have linked your virtual node-enocean-button like a real button.

**Comment by Jean-PhilippeD** [comment]
But I have 3 nodon modules in wall, how can a module knows the order is for him ?

**Comment by Jey-Cee** [comment]
Good and interessting Question. I don`t know. There is a destinationID in telegrams but it seems there will be allways used "ffffff" as id, that is a broadcast. 
Have you tested whats happening if you link the same virtual button to all 3 nodon modules?

**Comment by Holger-Will** [comment]
The easiest way to do this, is to set your nodeon module into learn mode, and the send a teach telegram...

if you realy want to send telegrams to a specific address, you can use my new [transcoder Module](https://github.com/node-enocean/eep-transcoder) to create an f6-02-03 button press telegram with a destination address:

    var tel ={
      decoded:{
          RA:{value:0x07}
       },
       _senderId: "aabbccdd", // your base id + offset
       _destinationId: "ddccbbaa" // the address of the device you want to send to
    }
    var enc = EnocenTelegram.encode(tel,"f6-02-03")
    enocean.send(enc.encoded)

P.S.: you can just send a teach in telegram to a sensor... you always have to start the teach in mode. For the nodon modules there are 3 ways to do this. With the button on the device, with an attached rocker-switch are via a remote command, which you can only send from a previously coupled sender...

**Comment by Jean-PhilippeD** [comment]
I think I undersant, in fact the virtual button should be bound to the nodon module ? 

While with FHEM I can send order to my module without button, that's what I was looking for.

But in this case, when I teach a new module "f6-02-03", I should create an associated button bound to it ?

**Comment by Jean-PhilippeD** [comment]
Ok I've changed my mind, I understand how it should works, even if with FHEM, i'm able to send command to any device withouth needed to bind/learn a device with a button.

Then, I have to : 

- create a node-enocean-button 
- put my nodon module in learning state
- bind the button with the module (**but how can I do this ??**, I've tried to send an order with the button, without success..)

Do you confirm ?

**Comment by Holger-Will** [comment]
The Teach in procedure is defined by the enocean specification. If you could send a  Telegramm to any actor without Teach in, that would be a huge Security risc. ![image](https://photos.app.goo.gl/wq66h316ChQUXUHC2) the procedure for your module is described  in your Nodon Handbook... though the nodon Handbook only mentions f6-02-01. The pre Build enocean-button can only send f6-02-03. Thats the most common rocker switch Telegramm and should Work as well...

**Comment by Jean-PhilippeD** [comment]
I understand what you say, but what I'm saying is that in FHEM instance, I just have to register my in-wall module on the FHEM configuration (with the id of the module), then I'm able to send order to this module from FHEM, not from a Rocker/Button.

What you're talking about is the ability to switch on the module just with another enocean device such as a rocker. But not from the USB TCM310 device.

**Comment by Jean-PhilippeD** [comment]
It works ! 

I just had to put the device in teach mode and send a A1.click() and it worked like a button !

Thanks for the explanations
