### ISSUE TITLE
Listener leak in memory.js

### ISSUE THREAD

**Issue by altery** [node-enocean/node-enocean#40]
# Symptom

If the same instance of the library is used with consecutive listen()/close() calls, there will be a listener leak on the main emitter (SerialPortListener).  Node will soon complain:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
```

# Analysis
The listener is installed as a side effect of creating the 'Memory':

index.js
```javascript
this.mem    = new Memory( this , { sensorFilePath : this.sensorFilePath, memoryDirectoryPath : config.memoryDirectoryPath } ) // initialize the Memory implementation used for learning an forgetting sensors. all meaningfull events are emitted there
```
memory.js
```
app.on( "data" , function( data ) {
    if ( knownSensors.hasOwnProperty( data.senderId )) { (...) }
(...)
}
```

# Expected behavior
close()-ing the SerialPortListener should also cleanup any listener installed in listen().

**Comment by Holger-Will** [comment]
spot on! nice find. fixed with latest commit.

**Comment by altery** [comment]
Great, thank you for the fix!
