### ISSUE TITLE
where to edit!!!!!!

### ISSUE THREAD

**Issue by Niazmorshed19** [node-enocean/node-enocean#41]
Where shuld i put this code. i didnt find any placce in my node red to write this code

var enocean      = require("node-enocean")();
enocean.listen("/dev/ttyUSB0");
enocean.on("data",function(data){   
	console.log(data)

});

**Comment by Holger-Will** [comment]
this module is not node-red specific. this is minimal code required for pure nodejs modules. please try [here](https://github.com/node-enocean/node-red-contrib-enocean), maybe someone can help you there.
